### ISSUE TITLE
Linux Ubuntu 18 - Linking error with MBE library

### ISSUE THREAD

**Issue by BenHenUnif** [nostar/dudestar#29] opened 2020-11-11 15:12 UTC
Hello,

I'm using Linux Ubuntu 18.04 on a Dell G3 laptop.
Compilation of DUDE-Star works fine, but linking fails with following error message : 
_g++ -Wl,-O1 -o dudestar CRCenc.o DMRData.o Golay24128.o SHA256.o YSFConvolution.o YSFFICH.o ambe.o cbptc19696.o cgolay2087.o chamming.o codebooks.o codec2.o kiss_fft.o lpc.o nlp.o pack.o qbase.o quantise.o crc.o crs129.o dmrencoder.o dudestar.o fec.o aux_sub.o basicop2.o ch_decode.o ch_encode.o dc_rmv.o decode.o dsp_sub.o encode.o imbe_vocoder.o math_sub.o pe_lpf.o pitch_est.o pitch_ref.o qnt_sub.o rand_gen.o sa_decode.o sa_encode.o sa_enh.o tbls.o uv_synt.o v_synt.o v_uv_det.o m17codec.o main.o mbedec.o mbeenc.o mbefec.o nxdnencoder.o p25encoder.o pn.o viterbi.o viterbi5.o ysfdec.o ysfenc.o qrc_dudestar.o moc_dudestar.o   -LC:\Qt\mbelib\build_x32 -LC:\Qt\mbelib\build_x64 -lmbe -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5SerialPort -lQt5Network -lQt5Core -lGL -lpthread
/usr/bin/ld: cannot find -lmbe
collect2: error: ld returned 1 exit status
Makefile:376: recipe for target 'dudestar' failed
make: *** [dudestar] Error 1_
Can anyone help me ? Where is this library ? Do I need to install or build it ?
Thanks and regards, Benoit
73 de ON3ZZT

**Comment by nostar** [comment] 2020-11-11 15:50
https://github.com/szechyjs/mbelib

**Comment by TychoSchenkeveld** [comment] 2020-11-19 01:29
I had this issue too, it's because of the C:\ paths :) You have to remove them, compile mbelib and include the directory where the compiled mbelib is placed.

**Comment by nostar** [comment] 2020-11-19 02:09
> I had this issue too, it's because of the C:\ paths :) On my Mac this doesn't exist :) You have to remove them, compile mbelib and include the directory where the compiled mbelib is placed.

That is incorrect.  The C:\ paths have nothing to do with it. the -L flag only adds locations to look for libs specified by -l, it doesn't over write any existing locations, and it doesn't matter if those places exist or not.  I leave those in there for my Windows build, but build on Linux just fine with those in there.

The problem is that when you install libraries from source, they are usually installed to /usr/local... instead of /usr...  The /usr/local paths are not included in your Linux operating systems LD_LIBRARY_PATH (or DYLD_LIBRARY_PATH on OSX).  Any Linux user that builds software from source knows to add /usr/local/lib and /usr/local/lib64 to the list of paths.  You can add the paths to the environment variable and have that done every login, but the better way on Linux is to use ldconfig:

Create a file called local.conf in /etc/ld.so.conf.d and add 2 lines:
/usr/local/lib
/usr/local/lib64

Save and close the file. It doesn't matter if one of these directories was empty or even if one of them was non existent.

then run the command 'ldconfig'

All of these needs root permissions, obviously. Once this is all done run make again and it should find the mbelib files and link successfully.  Any other libraries built from source and installed into /usr/local will also be found from this point on.

**Comment by TychoSchenkeveld** [comment] 2020-11-19 11:45
You're right, I checked and the C:\ paths were just a warning. Sorry. The issue was indeed that it coudn't find libmbe.

PS: Even with libmbe included and successfully compiled, it segfaults when I press the connect button, seems to be coming from the CoreAudio lib. I will raise a different ticket for it.

**Comment by nostar** [comment] 2020-11-28 09:10
Closing

**Closed by nostar** 2020-11-28 09:10 UTC
