### ISSUE TITLE
Compiling on Ubuntu 20.04

### ISSUE THREAD

**Issue by mlforcada** [nostar/dudestar#34] opened 2020-11-26 18:41 UTC
I'd like to compile this for GNU/Linux, in particular Ubuntu 20.04.
The instructions to use qmake and make (after installing all qt5 libraries), I get this error:

dudestar.h:30:10: fatal error: flite/flite.h: El fitxer o directori no existeix
   30 | #include <flite/flite.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:822: dudestar.o] Error 1

What did I do wrong?
Thanks!

**Comment by nostar** [comment] 2020-11-26 18:47
Open dudestar.pro and change the line
```
DEFINES += USE_FLITE
```
to
```
#DEFINES += USE_FLITE
```
Then run make clean, qmake, and make

**Comment by mlforcada** [comment] 2020-11-27 08:02
Thanks a million, nostar!
What I did was installing 
```
sudo apt-get install flite-dev
```
without commenting out that line in the dudestar.pro file and now it compiles and seems to work. 
Should I still comment out the USE_FLITE line and rebuild?

**Comment by nostar** [comment] 2020-11-28 17:58
Duplicate of #8

**Closed by nostar** 2020-11-28 17:58 UTC
